# Generated by Django 2.2 on 2019-12-07 12:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradingName', models.CharField(max_length=150)),
                ('ownerName', models.CharField(max_length=100)),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, unique=True)),
                ('coverageArea', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('endereco', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
