# Generated by Django 2.2 on 2019-12-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdv',
            old_name='endereco',
            new_name='address',
        ),
    ]
